#! /bin/bash


if [[ -d "/sys/class/power_supply/BAT0/" ]]; then
    folder="/sys/class/power_supply/BAT0/"
elif [[ -d "/sys/class/power_supply/BAT1/" ]]; then
    folder="/sys/class/power_supply/BAT1/"
fi

if [[ $(cat $folder"status") == "Charging" ]]; then
    cat $folder"capacity" 2> /dev/null | awk $'{print " \U26a1 "$0"% "}'
else
    cat $folder"capacity" 2> /dev/null | awk $'{print " "$0"% "}'
fi
